# Generated by Django 5.0.3 on 2024-03-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='items',
            field=models.ManyToManyField(null=True, to='app.groceryitem'),
        ),
    ]
